inherits:
  - duplicated
  - utils:base
  - utils:fix
  - utils:no-design-checks

ignore-patterns:
  - ^tilecloud/scripts/tc_.*.py
  - ^examples/.*.py

pylint:
  options:
    extension-pkg-allow-list: cairo
  disable:
    - cyclic-import # see: https://github.com/PyCQA/pylint/issues/850

mypy:
  options:
    python-version: '3.10'

ruff:
  options:
    target-version: py310
