inherits:
  - duplicated
  - utils:base
  - utils:fix
  - utils:no-design-checks
  - utils:unsafe

ignore-patterns:
  - ^tilecloud/scripts/tc_.*.py
  - ^examples/.*.py

pylint:
  disable:
    - cyclic-import # see: https://github.com/PyCQA/pylint/issues/850

ruff:
  disable:
    - D102 # Missing docstring in public method
    - D107 # Missing docstring in `__init__`
