strictness: veryhigh
doc-warnings: false
max-line-length: 110

pylint:
  options:
    max-line-length: 110
  disable:
    - too-many-instance-attributes
    - too-many-ancestors
    - too-many-return-statements
    - too-many-branches
    - too-many-arguments
    - too-many-locals
    - too-many-nested-blocks
    - too-few-public-methods
    - wrong-import-order
    - no-else-return
    - abstract-method
    - invalid-name
    - redefined-builtin
    - broad-except
    - cyclic-import # see: https://github.com/PyCQA/pylint/issues/850

pycodestyle:
  disable:
    - E203
    - E501

mypy:
  run: true

bandit:
  run: true
  options:
    config: .bandit.yaml

pyroma:
  run: true

mccabe:
  run: false
