inherits:
  - duplicated
  - utils:base
  - utils:no-design-checks

strictness: veryhigh
doc-warnings: false

ignore-patterns:
  - ^tilecloud/scripts/tc_.*.py
  - ^examples/.*.py

pylint:
  disable:
    - cyclic-import # see: https://github.com/PyCQA/pylint/issues/850

bandit:
  options:
    config: .bandit.yaml
