#!/usr/bin/env python

from itertools import imap
import logging
from optparse import OptionParser
import os.path
import sys

from tilecloud import BoundingPyramid, TileStore, consume
from tilecloud.filter.logger import Logger
from tilecloud.store.boundingpyramid import BoundingPyramidTileStore


def main(argv):
    logger = logging.getLogger(os.path.basename(argv[0]))
    option_parser = OptionParser()
    option_parser.add_option('-b', '--bounding-pyramid',
                             metavar='BOUNDING-PYRAMID')
    option_parser.add_option('-m', '--move', action='store_true')
    option_parser.add_option('-o', '--overwrite', action='store_true')
    option_parser.add_option('-v', '--verbose', action='store_true')
    options, args = option_parser.parse_args(argv[1:])
    if options.verbose:
        logging.basicConfig(level=logging.INFO)
    assert len(args) >= 2
    if options.bounding_pyramid:
        bounding_pyramid = \
                BoundingPyramid.from_string(options.bounding_pyramid)
    else:
        bounding_pyramid = None
    output_tile_store = TileStore.load(args[-1])
    for arg in args[:-1]:
        input_tile_store = TileStore.load(arg)
        if bounding_pyramid:
            tilestream = BoundingPyramidTileStore(bounding_pyramid).list()
            tilestream = input_tile_store.get(tilestream)
        else:
            tilestream = input_tile_store.get_all()
        if not options.overwrite:
            tilestream = (tile for tile in tilestream
                               if tile not in output_tile_store)
        tilestream = output_tile_store.put(tilestream)
        if options.move:
            tilestream = input_tile_store.delete(tilestream)
        if options.verbose:
            tilestream = imap(Logger(logger, logging.INFO, '%(tilecoord)s'), tilestream)
        consume(tilestream, None)


if __name__ == '__main__':
    sys.exit(main(sys.argv))
