#!/usr/bin/env python

from optparse import OptionParser
import sys

from tilecloud import BoundingPyramid, TileStore, consume
from tilecloud.store.boundingpyramid import BoundingPyramidTileStore


def main(argv):
    option_parser = OptionParser()
    option_parser.add_option('-b', '--bounding-pyramid',
                             metavar='BOUNDING-PYRAMID')
    options, args = option_parser.parse_args(argv[1:])
    assert len(args) >= 2
    if options.bounding_pyramid:
        bounding_pyramid = \
                BoundingPyramid.from_string(options.bounding_pyramid)
    else:
        bounding_pyramid = None
    output_tile_store = TileStore.load(args[-1])
    for arg in args[:-1]:
        input_tile_store = TileStore.load(arg)
        if bounding_pyramid:
            tilestream = BoundingPyramidTileStore(bounding_pyramid).list()
            tilestream = input_tile_store.get(tilestream)
        else:
            tilestream = input_tile_store.get_all()
        tilestream = output_tile_store.put(tilestream)
        consume(tilestream, None)


if __name__ == '__main__':
    sys.exit(main(sys.argv))
