---
version: 1
update_configs:
  - package_manager: python
    directory: /
    update_schedule: live
    allowed_updates:
      - match:
          dependency_type: direct
    automerged_updates:
      - match:
          update_type: all
    ignored_updates:
      - match:
          dependency_name: none
