# yaml-language-server: $schema=https://raw.githubusercontent.com/camptocamp/c2cciutils/master/c2cciutils/schema.json

checks:
  required_workflows:
    clean.yaml: False
    audit.yaml: False
    rebuild.yaml: False
  versions: False
  prospector_config:
    properties:
      doc-warnings: false

publish:
  docker:
    images: []
  pypi:
    versions:
      - version_tag
      - version_branch
