# yaml-language-server: $schema=https://raw.githubusercontent.com/camptocamp/c2cciutils/1.5.10/c2cciutils/schema.json

checks:
  versions: false
  codespell: false
  prettier: false

publish:
  docker:
    images: []
