# yaml-language-server: $schema=https://raw.githubusercontent.com/camptocamp/c2cciutils/1.1.31/c2cciutils/schema.json

checks:
  required_workflows: False
  versions: False
  black: false
  prospector_config: false
  editorconfig: false
  prettier: false

publish:
  docker:
    images: []
