# yaml-language-server: $schema=https://raw.githubusercontent.com/camptocamp/c2cciutils/1.1.33/c2cciutils/schema.json

checks:
  required_workflows: false
  versions: false
  prospector_config:
    properties:
      doc-warnings: false

  codespell: false
publish:
  docker:
    images: []
  pypi:
    versions:
      - version_tag
      - version_branch
