#!/bin/bash -e

if [ "${GITHUB_REF}" != "refs/tags/$(python3 setup.py --version)" ]; then
    echo "Ignore publishing on pypi"
    exit 0
fi

python3 -m pip install --requirement=requirements-publish.txt

echo Prepare .pypirc config
{
  echo "[distutils]"
  echo "index-servers = pypi"
  echo "[pypi]"
  echo "username:${USERNAME}"
  echo "password:${PASSWORD}"
} > ~/.pypirc

set -x

# Publish the Python eggs
python3 setup.py egg_info sdist bdist_wheel
twine upload dist/*

rm ~/.pypirc
