#!/bin/bash -e

if [ "${GITHUB_REF}" != "refs/tags/$(python3 setup.py --version)" ]
then
    echo "Ignore publishing on pypi"
    exit 0
fi


python3 -m pip install --requirement=requirements-publish.txt

echo  Prepare .pypirc config
echo "[distutils]" > ~/.pypirc
echo "index-servers = pypi" >> ~/.pypirc
echo "[pypi]" >> ~/.pypirc
echo "username:${USERNAME}" >> ~/.pypirc
echo "password:${PASSWORD}" >> ~/.pypirc

set -x

# Publish the Python eggs
python3 setup.py egg_info sdist bdist_wheel
twine upload dist/*

rm ~/.pypirc
