name: Auto reviews updates

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  auto-merge:
    name: Auto reviews updates
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - name: Auto reviews updates
        uses: golfzaptw/action-auto-reviews-from-branches@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AUTHOR: renovate[bot]
